name = "Cardio1D"
uuid = "60727eac-f7d1-4dc9-8583-3246d531585b"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
FFTW = "1.6"
julia = "1.8"
